version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: "increase"
    commit-message:
      prefix: "patch"
    groups:
       actions:
         pattern: "*"   